#!/bin/sh

lein run test \
    --workload register \
    --simulate cluster-scaler \
    --concurrency 60 \
    --keyspace 10 \
    --time-limit 900 \
    --havoc-delay 60 \
    --havoc-duration 60 \
    --ring-stable-delay 60 \
    --rate 1
